export const qashqadaryoListings: any[] = [
  {
    "id": 1051,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kitob-shahar-markazida-hashamatli-5-xonali-hovli",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"],
    "title": "Kitob shahar markazida hashamatli 5 xonali hovli",
    "price": "$120,000",
    "currency": "USD",
    "location": "Kitob shahar",
    "region": "Qashqadaryo",
    "district": "Kitob",
    "address": "Markaz",
    "rooms": 5,
    "size": 200,
    "type": "sale",
    "propertyType": "house",
    "isTop": true,
    "topExpiresAt": Date.now() + 86400000 * 7,
    "status": "approved",
    "description": "Kitob shahrining eng markazida joylashgan premium hovli. Barcha sharoitlar mavjud, yevro ta'mirlangan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "sellerTelegram": "@uybozori_admin1",
    "createdAt": Date.now()
  },
  {
    "id": 1052,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshi-shahrida-katta-va-keng-8-xonali-hovli",
    "image": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshi shahrida katta va keng 8 xonali hovli",
    "price": "$110,000",
    "currency": "USD",
    "location": "Qarshi",
    "region": "Qashqadaryo",
    "district": "Qarshi",
    "address": "Markaz",
    "rooms": 8,
    "size": 400,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Qarshi shahrida joylashgan juda katta hovli. Katta oilalar uchun juda mos keladi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "sellerTelegram": "@uybozori_admin1",
    "createdAt": Date.now() - 3600000
  },
  {
    "id": 1001,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshida-shahar-markazida-keng-hovli-sotiladi",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshida shahar markazida keng hovli sotiladi",
    "price": "$50,000",
    "currency": "USD",
    "location": "Qarshi, Yangiobod MFY",
    "region": "Qashqadaryo",
    "district": "Yangiobod MFY",
    "address": "Yangiobod MFY",
    "rooms": 5,
    "size": 250,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uy judayam pishiq qurilgan bo'lib, hovlisida mevali daraxtlari bor. Atrofda maktab, bog'cha va bozor piyoda yetib borish masofasida joylashgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now()
  },
  {
    "id": 1002,
    "userId": "demo-seller-qashqadaryo",
    "slug": "shahrisabzda-sifatli-tamirlangan-zamonaviy-uy",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    "title": "Shahrisabzda sifatli ta'mirlangan zamonaviy uy",
    "price": "$45,000",
    "currency": "USD",
    "location": "Shahrisabz, Oqsaroy MFY",
    "region": "Qashqadaryo",
    "district": "Oqsaroy MFY",
    "address": "Oqsaroy MFY",
    "rooms": 4,
    "size": 180,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Barcha qulayliklarga ega, ichki bezaklari yuqori sifatli materiallardan ishlangan. Yashash uchun to'liq tayyor, ko'chib kirish va yashash mumkin.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 1
  },
  {
    "id": 1003,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kitob-tumanida-katta-va-shinam-xonadon",
    "image": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"],
    "title": "Kitob tumanida katta va shinam xonadon",
    "price": "$35,000",
    "currency": "USD",
    "location": "Kitob, Guliston MFY",
    "region": "Qashqadaryo",
    "district": "Guliston MFY",
    "address": "Guliston MFY",
    "rooms": 6,
    "size": 220,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Qo'shnilar judayam yaxshi va mahalla tinch osoyishta. Qishda issiq, yozda salqin bo'ladigan ajoyib uy, avtomobil uchun garaj ham mavjud.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 2
  },
  {
    "id": 1004,
    "userId": "demo-seller-qashqadaryo",
    "slug": "yakkabogda-arzon-narxda-uy-zudlik-bilan-sotiladi",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0bcd2a6c4?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566753190-17f0bcd2a6c4?auto=format&fit=crop&w=800&q=80"],
    "title": "Yakkabog'da arzon narxda uy zudlik bilan sotiladi",
    "price": "$40,000",
    "currency": "USD",
    "location": "Yakkabog‘, Nuriston MFY",
    "region": "Qashqadaryo",
    "district": "Nuriston MFY",
    "address": "Nuriston MFY",
    "rooms": 4,
    "size": 150,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uy zudlik bilan chet elga ketayotganlik sababli arzon narxda sotilyapti. Suv, gaz, svet doimiy, muammo yo'q.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 3
  },
  {
    "id": 1005,
    "userId": "demo-seller-qashqadaryo",
    "slug": "guzorda-ixcham-va-fayzli-yashash-joyi",
    "image": "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80"],
    "title": "G'uzorda ixcham va fayzli yashash joyi",
    "price": "$32,000",
    "currency": "USD",
    "location": "G‘uzor, Sho'rtan MFY",
    "region": "Qashqadaryo",
    "district": "Sho'rtan MFY",
    "address": "Sho'rtan MFY",
    "rooms": 3,
    "size": 120,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Yosh oilalar uchun ajoyib boshlang'ich imkoniyat bo'lishi mumkin. Uy ichida yangi isitish tizimi o'rnatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 4
  },
  {
    "id": 1006,
    "userId": "demo-seller-qashqadaryo",
    "slug": "dehqonobod-tabiati-qoynida-katta-hovli",
    "image": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80"],
    "title": "Dehqonobod tabiati qo'ynida katta hovli",
    "price": "$42,000",
    "currency": "USD",
    "location": "Dehqonobod, Oqrabod MFY",
    "region": "Qashqadaryo",
    "district": "Oqrabod MFY",
    "address": "Oqrabod MFY",
    "rooms": 5,
    "size": 280,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Katta yer maydoniga ega bo'lgan bu uy dehqonchilik qilish uchun qulay. Havosi toza, shovqindan uzoqda dam olib yashash uchun zo'r joy.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 5
  },
  {
    "id": 1007,
    "userId": "demo-seller-qashqadaryo",
    "slug": "nishonda-barcha-sharoitlarga-ega-shinam-uy",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    "title": "Nishonda barcha sharoitlarga ega shinam uy",
    "price": "$28,000",
    "currency": "USD",
    "location": "Nishon, Nurobod MFY",
    "region": "Qashqadaryo",
    "district": "Nurobod MFY",
    "address": "Nurobod MFY",
    "rooms": 3,
    "size": 140,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uyni o'zimiz uchun sifatli qilib qurganmiz, biroq pul zarurligi uchun sotilyapti. Ayrim mebellar xaridorga sovg'a sifatida qoldiriladi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 6
  },
  {
    "id": 1008,
    "userId": "demo-seller-qashqadaryo",
    "slug": "koson-tumanida-tayyor-yashash-uchun-mos-xonadon",
    "image": "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=800&q=80"],
    "title": "Koson tumanida tayyor, yashash uchun mos xonadon",
    "price": "$38,000",
    "currency": "USD",
    "location": "Koson, Navbahor MFY",
    "region": "Qashqadaryo",
    "district": "Navbahor MFY",
    "address": "Navbahor MFY",
    "rooms": 4,
    "size": 170,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Pishiq g'ishtdan qurilgan uy va usti sifatli tunuka bilan yopilgan. Keng va katta mehmonxonasi mehmon kutishni sevuvchilar uchun ideal.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 7
  },
  {
    "id": 1009,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kasbi-tumanida-daromad-keltiruvchi-tayyor-issiqxonali-uy",
    "image": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80"],
    "title": "Kasbi tumanida daromad keltiruvchi tayyor issiqxonali uy",
    "price": "$31,000",
    "currency": "USD",
    "location": "Kasbi, Fazilat MFY",
    "region": "Qashqadaryo",
    "district": "Fazilat MFY",
    "address": "Fazilat MFY",
    "rooms": 4,
    "size": 200,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Hovlida yil davomida ishlaydigan va daromad keltiradigan issiqxona tayyor qilingan. Shuningdek, uy ham to'liq va sifatli yevro ta'mirdan chiqqan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 8
  },
  {
    "id": 1010,
    "userId": "demo-seller-qashqadaryo",
    "slug": "mirishkor-markazida-keng-oilaviy-uy",
    "image": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80"],
    "title": "Mirishkor markazida keng oilaviy uy",
    "price": "$29,000",
    "currency": "USD",
    "location": "Mirishkor, Jeynov MFY",
    "region": "Qashqadaryo",
    "district": "Jeynov MFY",
    "address": "Jeynov MFY",
    "rooms": 3,
    "size": 130,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Transport infratuzilmasi yaxshi joylashgan, ko'chalar asfalt qilingan. Uyda internet, telefon tarmog'i va kabel televideniyasi mavjud.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 9
  },
  {
    "id": 1011,
    "userId": "demo-seller-qashqadaryo",
    "slug": "muborak-tumanida-nufuzli-kochada-hovli-sotiladi",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"],
    "title": "Muborak tumanida nufuzli ko'chada hovli sotiladi",
    "price": "$47,000",
    "currency": "USD",
    "location": "Muborak, Mash'al MFY",
    "region": "Qashqadaryo",
    "district": "Mash'al MFY",
    "address": "Mash'al MFY",
    "rooms": 5,
    "size": 240,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Hovli to'liq betonlangan va old qismi go'zal landshaftga ega. Xavfsizlik maqsadida videokuzatuv kameralari o'rnatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 10
  },
  {
    "id": 1012,
    "userId": "demo-seller-qashqadaryo",
    "slug": "chiroqchida-hamyonbop-va-qulay-sharoitli-hovli",
    "image": "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80"],
    "title": "Chiroqchida hamyonbop va qulay sharoitli hovli",
    "price": "$34,000",
    "currency": "USD",
    "location": "Chiroqchi, Langar MFY",
    "region": "Qashqadaryo",
    "district": "Langar MFY",
    "address": "Langar MFY",
    "rooms": 4,
    "size": 160,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Asosiy yo'lga va do'konlarga yaqin, juda qulay hududda joylashgan. Oshxona jihozlari va qishki tayyorgarlik uchun alohida erto'lasi bor.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 11
  },
  {
    "id": 1013,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshining-markazida-hashamatli-dangillama-hovli",
    "image": "https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshining markazida hashamatli dang'illama hovli",
    "price": "$65,000",
    "currency": "USD",
    "location": "Qarshi, Nasaf MFY",
    "region": "Qashqadaryo",
    "district": "Nasaf MFY",
    "address": "Nasaf MFY",
    "rooms": 7,
    "size": 350,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "O'zining shaxsiy hovuziga va yozgi dam olish terassasiga ega ajoyib villa. Barcha santexnika va elektrik ishlari Yevropa standartida bajarilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 12
  },
  {
    "id": 1014,
    "userId": "demo-seller-qashqadaryo",
    "slug": "shahrisabz-kochalaridan-birida-gozal-uy",
    "image": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80"],
    "title": "Shahrisabz ko'chalaridan birida go'zal uy",
    "price": "$55,000",
    "currency": "USD",
    "location": "Shahrisabz, Kesh MFY",
    "region": "Qashqadaryo",
    "district": "Kesh MFY",
    "address": "Kesh MFY",
    "rooms": 5,
    "size": 210,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Tarix va zamonaviylik uyg'unlashgan dizayn, to'liq jihozlar bilan sotiladi. Hovlisiga ikki mashina bemalol sig'adi, atrofi yopiq va ishonchli.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 13
  },
  {
    "id": 1015,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kitobda-yorug-va-shinam-oilaviy-yashash-joyi",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    "title": "Kitobda yorug' va shinam oilaviy yashash joyi",
    "price": "$46,000",
    "currency": "USD",
    "location": "Kitob, Beshyog'och MFY",
    "region": "Qashqadaryo",
    "district": "Beshyog'och MFY",
    "address": "Beshyog'och MFY",
    "rooms": 4,
    "size": 190,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Quyosh nuri kun davomida uyga yaxshi tushadi, xonalar juda yorug'. Pol qismi sifatli laminat qoplama bilan qilingan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 14
  },
  {
    "id": 1016,
    "userId": "demo-seller-qashqadaryo",
    "slug": "yakkabog-tumanida-qoshimcha-imoratlari-bor-uy",
    "image": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"],
    "title": "Yakkabog' tumanida qo'shimcha imoratlari bor uy",
    "price": "$51,000",
    "currency": "USD",
    "location": "Yakkabog‘, Chaqar MFY",
    "region": "Qashqadaryo",
    "district": "Chaqar MFY",
    "address": "Chaqar MFY",
    "rooms": 5,
    "size": 230,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Mol-qo'y saqlash uchun orqa hovlida katta og'ilxona tiklangan. Yaqinda yangi tomlar yopilib, tashqi ko'rinishi yangilangan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 15
  },
  {
    "id": 1017,
    "userId": "demo-seller-qashqadaryo",
    "slug": "guzorda-ekinzorli-tayyor-uy-zudlikda-beriladi",
    "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80"],
    "title": "G'uzorda ekinzorli tayyor uy zudlikda beriladi",
    "price": "$33,000",
    "currency": "USD",
    "location": "G‘uzor, Pachkamar MFY",
    "region": "Qashqadaryo",
    "district": "Pachkamar MFY",
    "address": "Pachkamar MFY",
    "rooms": 3,
    "size": 125,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Hovlidagi ko'katlar va boshqa ekinlardan doimiy tarzda oilaviy ehtiyoj uchun foydalanish mumkin. Kanalizatsiya tarmog'i yangilangan va hovli toza.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 16
  },
  {
    "id": 1018,
    "userId": "demo-seller-qashqadaryo",
    "slug": "dehqonobod-sokin-tabiatida-gozal-maskan",
    "image": "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80"],
    "title": "Dehqonobod sokin tabiatida go'zal maskan",
    "price": "$39,000",
    "currency": "USD",
    "location": "Dehqonobod, Qorashina MFY",
    "region": "Qashqadaryo",
    "district": "Qorashina MFY",
    "address": "Qorashina MFY",
    "rooms": 4,
    "size": 180,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Havo harorati har doim a'lo darajada va toza kislorodga boy joy. Yozgi oqshomlarda o'tirish uchun maxsus yopiq so'ri qurilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 17
  },
  {
    "id": 1019,
    "userId": "demo-seller-qashqadaryo",
    "slug": "nishon-tumanida-ixcham-tamirlangan-yashash-maydoni",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80"],
    "title": "Nishon tumanida ixcham ta'mirlangan yashash maydoni",
    "price": "$30,000",
    "currency": "USD",
    "location": "Nishon, Paxtakor MFY",
    "region": "Qashqadaryo",
    "district": "Paxtakor MFY",
    "address": "Paxtakor MFY",
    "rooms": 3,
    "size": 110,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Kichik oilalar uchun ortiqcha harajatsiz yashash uchun juda to'g'ri tanlov. Elektr ta'minoti va gaz umuman uzilmaydigan mahallada.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 18
  },
  {
    "id": 1020,
    "userId": "demo-seller-qashqadaryo",
    "slug": "koson-shahriga-yaqin-joylashgan-fayzli-xonadon",
    "image": "https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80"],
    "title": "Koson shahriga yaqin joylashgan fayzli xonadon",
    "price": "$43,000",
    "currency": "USD",
    "location": "Koson, Pudina MFY",
    "region": "Qashqadaryo",
    "district": "Pudina MFY",
    "address": "Pudina MFY",
    "rooms": 6,
    "size": 250,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uyning hovlisida ikkita alohida issiq suv bilan isitiladigan hammom bor. Katta oilalar bemalol sig'adigan 6 ta yashash xonasidan iborat.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 19
  },
  {
    "id": 1021,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kasbi-hududida-yaxshi-sharoitli-va-manzarali-uy",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80"],
    "title": "Kasbi hududida yaxshi sharoitli va manzarali uy",
    "price": "$37,000",
    "currency": "USD",
    "location": "Kasbi, Qamashi MFY",
    "region": "Qashqadaryo",
    "district": "Qamashi MFY",
    "address": "Qamashi MFY",
    "rooms": 4,
    "size": 160,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Katta ko'chaga yaqin bo'lganligi uchun savdo do'koni ochishga juda mos. Derazalari va eshiklari yuqori sifatli akfa romlaridan qilingan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 20
  },
  {
    "id": 1022,
    "userId": "demo-seller-qashqadaryo",
    "slug": "mirishkorda-toliq-pishiq-gishtli-uzoq-umrli-uy",
    "image": "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80"],
    "title": "Mirishkorda to'liq pishiq g'ishtli uzoq umrli uy",
    "price": "$41,000",
    "currency": "USD",
    "location": "Mirishkor, Pomuq MFY",
    "region": "Qashqadaryo",
    "district": "Pomuq MFY",
    "address": "Pomuq MFY",
    "rooms": 5,
    "size": 200,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Poydevori juda mustahkam qilingan va keyinchalik ikkinchi qavatni ko'tarish imkoniyati bor. Bog'da gilos va yong'oq daraxtlari hosilga kirgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 21
  },
  {
    "id": 1023,
    "userId": "demo-seller-qashqadaryo",
    "slug": "muborakning-tinch-mahallasida-zamonaviy-jihozlangan-uy",
    "image": "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80"],
    "title": "Muborakning tinch mahallasida zamonaviy jihozlangan uy",
    "price": "$48,000",
    "currency": "USD",
    "location": "Muborak, Qoraqum MFY",
    "region": "Qashqadaryo",
    "district": "Qoraqum MFY",
    "address": "Qoraqum MFY",
    "rooms": 4,
    "size": 175,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Yangi kelin-kuyovlar uchun ajoyib qilib dizayn berilgan shinam hovli. Atrofida savdo markazlari va sport majmuasi faoliyat olib boradi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 22
  },
  {
    "id": 1024,
    "userId": "demo-seller-qashqadaryo",
    "slug": "chiroqchida-hovlisi-keng-va-chiroyli-kottej",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80"],
    "title": "Chiroqchida hovlisi keng va chiroyli kottej",
    "price": "$36,000",
    "currency": "USD",
    "location": "Chiroqchi, Sho'rquduq MFY",
    "region": "Qashqadaryo",
    "district": "Sho'rquduq MFY",
    "address": "Sho'rquduq MFY",
    "rooms": 3,
    "size": 145,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Er maydoni kattaligi sababli uy hayvonlari saqlashga yoki yangi bino qurishga qulay. Narxi kelishiladigan va ozgina kami bor xonadon.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 23
  },
  {
    "id": 1025,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshining-sokin-mavzesida-eksklyuziv-taklif",
    "image": "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshining sokin mavzesida eksklyuziv taklif",
    "price": "$75,000",
    "currency": "USD",
    "location": "Qarshi, Qavali MFY",
    "region": "Qashqadaryo",
    "district": "Qavali MFY",
    "address": "Qavali MFY",
    "rooms": 8,
    "size": 380,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Binoning tashqi fasadi to'liq travertin bilan ishlov berilgan va obodonlashtirilgan. Katta mehmonxona, maxsus xobbixona va ikkita avtomobilga mo'ljallangan yopiq garaj bor.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 24
  },
  {
    "id": 1026,
    "userId": "demo-seller-qashqadaryo",
    "slug": "shahrisabzda-sifatli-qulayliklarga-boy-shinam-hovli",
    "image": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80"],
    "title": "Shahrisabzda sifatli qulayliklarga boy shinam hovli",
    "price": "$58,000",
    "currency": "USD",
    "location": "Shahrisabz, Zarkent MFY",
    "region": "Qashqadaryo",
    "district": "Zarkent MFY",
    "address": "Zarkent MFY",
    "rooms": 5,
    "size": 220,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Sanuzellar ichkarida qilingan va sifatli kafel qoplamalari bilan bezatilgan. Qish oylarida butun uy bo'ylab 'issiq pol' tizimi yoqib qo'yiladi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 25
  },
  {
    "id": 1027,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kitob-toglari-manzarasi-ostida-gozal-uy",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"],
    "title": "Kitob tog'lari manzarasi ostida go'zal uy",
    "price": "$49,000",
    "currency": "USD",
    "location": "Kitob, Obi-gardon MFY",
    "region": "Qashqadaryo",
    "district": "Obi-gardon MFY",
    "address": "Obi-gardon MFY",
    "rooms": 4,
    "size": 195,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Sayyohlik zonasiga yaqin joyda joylashgani uchun turistik ijaraga ham berish mumkin. Uyning orqa tomonida kichik ariq oqib o'tadi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 26
  },
  {
    "id": 1028,
    "userId": "demo-seller-qashqadaryo",
    "slug": "yakkabogda-fayzli-qishloq-sharoitiga-ega-zamonaviy-uy",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    "title": "Yakkabog'da fayzli qishloq sharoitiga ega zamonaviy uy",
    "price": "$53,000",
    "currency": "USD",
    "location": "Yakkabog‘, Turkiston MFY",
    "region": "Qashqadaryo",
    "district": "Turkiston MFY",
    "address": "Turkiston MFY",
    "rooms": 6,
    "size": 260,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Ichki ishlari shahar standartlariga mos, tashqarisi esa qishloq tabiatiga boy qilib tiklangan. Elektr tarmoqlaridan uzilishlar umuman kuzatilmaydi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 27
  },
  {
    "id": 1029,
    "userId": "demo-seller-qashqadaryo",
    "slug": "guzorda-tamiri-yangi-oilaviy-hovli",
    "image": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"],
    "title": "G'uzorda ta'miri yangi oilaviy hovli",
    "price": "$31,500",
    "currency": "USD",
    "location": "G‘uzor, Zarbdor MFY",
    "region": "Qashqadaryo",
    "district": "Zarbdor MFY",
    "address": "Zarbdor MFY",
    "rooms": 3,
    "size": 115,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Yaqlinda to'liq kosmetik ta'mirdan chiqqan, hali hech kim yashamagan toza xonadon. Darvozadan kirish qismi chiroyli arklar va tok novdalari bilan bezatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 28
  },
  {
    "id": 1030,
    "userId": "demo-seller-qashqadaryo",
    "slug": "dehqonobodda-mevali-bogu-rogli-uy-sotiladi",
    "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80"],
    "title": "Dehqonobodda mevali bog'u-rog'li uy sotiladi",
    "price": "$40,500",
    "currency": "USD",
    "location": "Dehqonobod, Tarkapchigay MFY",
    "region": "Qashqadaryo",
    "district": "Tarkapchigay MFY",
    "address": "Tarkapchigay MFY",
    "rooms": 4,
    "size": 300,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uyning asosiy ustunligi - bu yuzlab tupdan ortiq turli xil mevali daraxtlarga ega bog'dir. Toza tabiat ixlosmandlari uchun aynan mos tushadigan manzil.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 29
  },
  {
    "id": 1031,
    "userId": "demo-seller-qashqadaryo",
    "slug": "nishonda-narxi-arzon-ammo-sifatli-hovli",
    "image": "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80"],
    "title": "Nishonda narxi arzon, ammo sifatli hovli",
    "price": "$29,500",
    "currency": "USD",
    "location": "Nishon, Shirinobod MFY",
    "region": "Qashqadaryo",
    "district": "Shirinobod MFY",
    "address": "Shirinobod MFY",
    "rooms": 3,
    "size": 135,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Shahar markazidan bir oz uzoqroqda, lekin transport harakati juda yaxshi yo'lga qo'yilgan. Atrofida poliklinika va savdo majmualari bir qadam masofada.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 30
  },
  {
    "id": 1032,
    "userId": "demo-seller-qashqadaryo",
    "slug": "koson-shahrida-mukammal-poydevorli-bino",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80"],
    "title": "Koson shahrida mukammal poydevorli bino",
    "price": "$44,000",
    "currency": "USD",
    "location": "Koson, Oqtepa MFY",
    "region": "Qashqadaryo",
    "district": "Oqtepa MFY",
    "address": "Oqtepa MFY",
    "rooms": 5,
    "size": 215,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uyning pastki erto'lasi butun xonalar ostida keng o'rin egallagan va sport zali uchun ishlatilishi mumkin. Hovli juda obod hamda saranjom saqlangan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 31
  },
  {
    "id": 1033,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kasbida-biznes-maqsadlarga-mos-er-uchastkasi-va-uy",
    "image": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"],
    "title": "Kasbida biznes maqsadlarga mos er uchastkasi va uy",
    "price": "$37,500",
    "currency": "USD",
    "location": "Kasbi, Maymanoq MFY",
    "region": "Qashqadaryo",
    "district": "Maymanoq MFY",
    "address": "Maymanoq MFY",
    "rooms": 4,
    "size": 270,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Er maydoni juda katta va burchakda joylashgani uchun sex yoki kichik korxona qurishga qulay. Uy qismi hozir ham yashashga to'liq javob beradigan holatda.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 32
  },
  {
    "id": 1034,
    "userId": "demo-seller-qashqadaryo",
    "slug": "mirishkorda-hovlisi-gulzorga-aylantirilgan-uy",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80"],
    "title": "Mirishkorda hovlisi gulzorga aylantirilgan uy",
    "price": "$42,500",
    "currency": "USD",
    "location": "Mirishkor, Chandir MFY",
    "region": "Qashqadaryo",
    "district": "Chandir MFY",
    "address": "Chandir MFY",
    "rooms": 4,
    "size": 185,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Turli xil manzarali gullar ekilgan go'zal hovli va qulay dam olish zonasi bor. Oshxonada havo tortgich, yangi mebellar va sifatli maishiy texnikalar mavjud.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 33
  },
  {
    "id": 1035,
    "userId": "demo-seller-qashqadaryo",
    "slug": "muborak-kochalarining-birida-tayyor-dizaynerlik-uyi",
    "image": "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80"],
    "title": "Muborak ko'chalarining birida tayyor dizaynerlik uyi",
    "price": "$49,500",
    "currency": "USD",
    "location": "Muborak, Geolog MFY",
    "region": "Qashqadaryo",
    "district": "Geolog MFY",
    "address": "Geolog MFY",
    "rooms": 5,
    "size": 235,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Maxsus dizayn proyekt orqali ta'mirlangan, har bir xona o'ziga xos uslubga ega. Barcha xonalarga avtomatik iqlim nazorati apparati o'rnatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 34
  },
  {
    "id": 1036,
    "userId": "demo-seller-qashqadaryo",
    "slug": "chiroqchi-obod-mahallasida-yorug-va-issiq-xonadon",
    "image": "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80"],
    "title": "Chiroqchi obod mahallasida yorug' va issiq xonadon",
    "price": "$36,500",
    "currency": "USD",
    "location": "Chiroqchi, Umakay MFY",
    "region": "Qashqadaryo",
    "district": "Umakay MFY",
    "address": "Umakay MFY",
    "rooms": 4,
    "size": 165,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Qalin devorlar uyni qishda yaxshi isitadi, yozda esa salqin saqlaydi. Elektr toki va gaz ulanishi uchun shaxsiy podstansiya o'rnatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 35
  },
  {
    "id": 1037,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshi-shahrining-nufuzli-mavzesidagi-villa",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0bcd2a6c4?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566753190-17f0bcd2a6c4?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshi shahrining nufuzli mavzesidagi villa",
    "price": "$85,000",
    "currency": "USD",
    "location": "Qarshi, Otchopar MFY",
    "region": "Qashqadaryo",
    "district": "Otchopar MFY",
    "address": "Otchopar MFY",
    "rooms": 8,
    "size": 400,
    "type": "sale",
    "propertyType": "house",
    "isTop": true,
    "topExpiresAt": Date.now() + 86400000 * 7,
    "status": "approved",
    "description": "Premium darajadagi xaridorlar uchun ikki qavatli, basseyn va sauna bilan jihozlangan hovli. Mehmonlar kutish xonasi juda katta maydonni egallagan va hashamatli qandillar o'rnatilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 36
  },
  {
    "id": 1038,
    "userId": "demo-seller-qashqadaryo",
    "slug": "shahrisabzda-barcha-shart-sharoitlarga-ega-ikki-qavatli-uy",
    "image": "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?auto=format&fit=crop&w=800&q=80"],
    "title": "Shahrisabzda barcha shart-sharoitlarga ega ikki qavatli uy",
    "price": "$62,000",
    "currency": "USD",
    "location": "Shahrisabz, Tepa MFY",
    "region": "Qashqadaryo",
    "district": "Tepa MFY",
    "address": "Tepa MFY",
    "rooms": 6,
    "size": 280,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Ikkinchi qavatdan tog'lar manzarasi juda ajoyib ko'rinadi. Ko'cha asfatlangan bo'lib, uy atrofi to'liq ko'kalamzorlashtirilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 37
  },
  {
    "id": 1039,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kitob-kochalarida-katta-imkoniyatlarga-ega-kottej",
    "image": "https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600585154542-6379b74b401c?auto=format&fit=crop&w=800&q=80"],
    "title": "Kitob ko'chalarida katta imkoniyatlarga ega kottej",
    "price": "$51,500",
    "currency": "USD",
    "location": "Kitob, Sariosiyo MFY",
    "region": "Qashqadaryo",
    "district": "Sariosiyo MFY",
    "address": "Sariosiyo MFY",
    "rooms": 5,
    "size": 210,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "O'zining ko'rinishi bilan boshqa uylardan ajralib turadigan go'zal kottej. Xonalar keng va shifti ancha baland qilib barpo etilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 38
  },
  {
    "id": 1040,
    "userId": "demo-seller-qashqadaryo",
    "slug": "yakkabogda-tinchliksevar-oilalar-uchun-osoyishta-maskan",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"],
    "title": "Yakkabog'da tinchliksevar oilalar uchun osoyishta maskan",
    "price": "$54,000",
    "currency": "USD",
    "location": "Yakkabog‘, Mustaqillik MFY",
    "region": "Qashqadaryo",
    "district": "Mustaqillik MFY",
    "address": "Mustaqillik MFY",
    "rooms": 5,
    "size": 225,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Mahalla odamlari juda samimiy va ko'chalar tungi chiroqlar bilan yoritilgan. Uy hovlisida ikkita alohida tapchan va tandirxona barpo etilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 39
  },
  {
    "id": 1041,
    "userId": "demo-seller-qashqadaryo",
    "slug": "guzor-markazida-hamyonbop-shinam-hovli-zudlik-bilan",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
    "title": "G'uzor markazida hamyonbop shinam hovli zudlik bilan",
    "price": "$32,500",
    "currency": "USD",
    "location": "G‘uzor, Muborak MFY",
    "region": "Qashqadaryo",
    "district": "Muborak MFY",
    "address": "Muborak MFY",
    "rooms": 3,
    "size": 130,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Barcha kommunikatsiyalar ulangan, umuman yashash uchun to'siq yo'q. Faqat tez sotish maqsadida bozor narxidan sezilarli darajada tushirib beriladi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 40
  },
  {
    "id": 1042,
    "userId": "demo-seller-qashqadaryo",
    "slug": "dehqonobodda-manzarali-landshaft-dizaynli-yashash-joyi",
    "image": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"],
    "title": "Dehqonobodda manzarali landshaft dizaynli yashash joyi",
    "price": "$41,500",
    "currency": "USD",
    "location": "Dehqonobod, Beshbuloq MFY",
    "region": "Qashqadaryo",
    "district": "Beshbuloq MFY",
    "address": "Beshbuloq MFY",
    "rooms": 4,
    "size": 190,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Sun'iy sharshara va yashil maydon hovliga o'ziga xos go'zallik baxsh etadi. Shuningdek, qo'shimcha bino qilib mehmonlar uchun alohida hujra qurilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 41
  },
  {
    "id": 1043,
    "userId": "demo-seller-qashqadaryo",
    "slug": "nishonda-uzoq-yillar-xizmat-qiladigan-gishtli-uy",
    "image": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80"],
    "title": "Nishonda uzoq yillar xizmat qiladigan g'ishtli uy",
    "price": "$30,500",
    "currency": "USD",
    "location": "Nishon, Balxiyak MFY",
    "region": "Qashqadaryo",
    "district": "Balxiyak MFY",
    "address": "Balxiyak MFY",
    "rooms": 3,
    "size": 125,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uzoq muddat o'z mustahkamligini yo'qotmaydigan zamonaviy qurilish mollari ishlatilgan. Derazalarga temir panjaralar va darvozaga sifatli avtomatik qulf qo'yilgan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 42
  },
  {
    "id": 1044,
    "userId": "demo-seller-qashqadaryo",
    "slug": "koson-shahrining-osoyishta-kochasidagi-tayyor-uy",
    "image": "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&w=800&q=80"],
    "title": "Koson shahrining osoyishta ko'chasidagi tayyor uy",
    "price": "$45,000",
    "currency": "USD",
    "location": "Koson, Guvalak MFY",
    "region": "Qashqadaryo",
    "district": "Guvalak MFY",
    "address": "Guvalak MFY",
    "rooms": 5,
    "size": 205,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Oila xavfsizligi va qulayligini birinchi o'ringa qo'yib loyihalashtirilgan. Maktab o'quvchilari uchun uy yonida zamonaviy sport va o'yin maydonchasi qurilmoqda.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 43
  },
  {
    "id": 1045,
    "userId": "demo-seller-qashqadaryo",
    "slug": "kasbida-toy-qilib-yashash-uchun-eng-qulay-variant",
    "image": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80"],
    "title": "Kasbida to'y qilib yashash uchun eng qulay variant",
    "price": "$38,500",
    "currency": "USD",
    "location": "Kasbi, Xo'jakasbi MFY",
    "region": "Qashqadaryo",
    "district": "Xo'jakasbi MFY",
    "address": "Xo'jakasbi MFY",
    "rooms": 4,
    "size": 215,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "To'ylar o'tkazish, mehmon kutish uchun hovli maydoni yetarli darajada katta. Uyni yozgi oshxonasida ikkita qozon o'choq va milliy tandir tayyor qilingan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 44
  },
  {
    "id": 1046,
    "userId": "demo-seller-qashqadaryo",
    "slug": "mirishkor-tumanida-yangi-dizayndagi-zamonaviy-uy",
    "image": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"],
    "title": "Mirishkor tumanida yangi dizayndagi zamonaviy uy",
    "price": "$43,500",
    "currency": "USD",
    "location": "Mirishkor, Avazcho'l MFY",
    "region": "Qashqadaryo",
    "district": "Avazcho'l MFY",
    "address": "Avazcho'l MFY",
    "rooms": 5,
    "size": 195,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Hozirgi vaqtda trendda bo'lgan ochiq ranglar uyg'unligida ichki ta'mirlash o'tkazilgan. Uy ichida alohida kiyim almashtirish xonasi va katta dahliz bor.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 45
  },
  {
    "id": 1047,
    "userId": "demo-seller-qashqadaryo",
    "slug": "muborakning-markaziy-yolga-yaqin-kochasida-uylar",
    "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80"],
    "title": "Muborakning markaziy yo'lga yaqin ko'chasida uylar",
    "price": "$50,500",
    "currency": "USD",
    "location": "Muborak, Qorabog' MFY",
    "region": "Qashqadaryo",
    "district": "Qorabog' MFY",
    "address": "Qorabog' MFY",
    "rooms": 5,
    "size": 230,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Asosiy trassa yoqasida bo'lishiga qaramay ichki xonalarda umuman shovqin eshitilmaydi. Mashinalar uchun xavfsiz to'xtash joyi va alohida darvozasi bor.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 46
  },
  {
    "id": 1048,
    "userId": "demo-seller-qashqadaryo",
    "slug": "chiroqchi-sokinligidagi-gozal-va-arzon-xonadon",
    "image": "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80"],
    "title": "Chiroqchi sokinligidagi go'zal va arzon xonadon",
    "price": "$35,500",
    "currency": "USD",
    "location": "Chiroqchi, Qalqama MFY",
    "region": "Qashqadaryo",
    "district": "Qalqama MFY",
    "address": "Qalqama MFY",
    "rooms": 3,
    "size": 155,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Qishloq xo'jaligi va shaxsiy tomorqa uchun mo'ljallangan yerni o'z ichiga oladi. Uyni sotib oluvchilar uchun uy hujjatlari to'liq va muammosiz tayyorlangan.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 47
  },
  {
    "id": 1049,
    "userId": "demo-seller-qashqadaryo",
    "slug": "qarshida-dabdabali-yangi-qurilgan-koshona-sotiladi",
    "image": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80"],
    "title": "Qarshida dabdabali yangi qurilgan koshona sotiladi",
    "price": "$95,000",
    "currency": "USD",
    "location": "Qarshi, Shodlik MFY",
    "region": "Qashqadaryo",
    "district": "Shodlik MFY",
    "address": "Shodlik MFY",
    "rooms": 8,
    "size": 390,
    "type": "sale",
    "propertyType": "house",
    "isTop": true,
    "topExpiresAt": Date.now() + 86400000 * 7,
    "status": "approved",
    "description": "Ushbu imorat shaharning eng qimmat mavzelaridan birida qad rostlagan bo'lib, o'zining dizayni bilan ajralib turadi. Faqat sifatni qadrlaydigan premium xaridorlar uchun eksklyuziv taklif hisoblanadi.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 48
  },
  {
    "id": 1050,
    "userId": "demo-seller-qashqadaryo",
    "slug": "shahrisabz-tarixiy-kochalarida-fayzli-yangi-uy",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
    "images": ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80"],
    "title": "Shahrisabz tarixiy ko'chalarida fayzli yangi uy",
    "price": "$64,000",
    "currency": "USD",
    "location": "Shahrisabz, Ipak yo'li MFY",
    "region": "Qashqadaryo",
    "district": "Ipak yo'li MFY",
    "address": "Ipak yo'li MFY",
    "rooms": 6,
    "size": 255,
    "type": "sale",
    "propertyType": "house",
    "status": "approved",
    "description": "Uy qadimiy obidalarga piyoda borish mumkin bo'lgan uzoqlikda joylashgan, shu bilan birga u mutlaqo zamonaviy. Xorijiy mehmonlarni ijaraga qo'yib yaxshi biznes qilishga juda yaxshi tanlov.",
    "sellerName": "Qashqadaryo Uy Bozori",
    "sellerPhone": "+998 90 000 00 00",
    "createdAt": Date.now() - 86400000 * 49
  }
];
